// Flat ESLint config. Lints TS/TSX across the repo; skips generated output.
// Kept non-type-checked (no parserOptions.project) so it stays fast — `tsc`
// already covers type correctness via `pnpm typecheck`.
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'

export default tseslint.config(
  {
    ignores: [
      'dist',
      '.output',
      '.tanstack',
      '.nitro',
      'node_modules',
      'src/routeTree.gen.ts', // generated by the TanStack Router plugin
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
)
