/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard/records'
import { Route as DashboardPaceRouteImport } from './routes/dashboard/pace'
import { Route as DashboardHeartRateRouteImport } from './routes/dashboard/heart-rate'
import { Route as DashboardCadenceRouteImport } from './routes/dashboard/cadence'
import { Route as DashboardActivitiesRouteImport } from './routes/dashboard/activities'
import { Route as AuthStravaRouteImport } from './routes/auth/strava'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiSyncStreamRouteImport } from './routes/api/sync/stream'
import { Route as ApiStravaWebhookRouteImport } from './routes/api/strava/webhook'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaceRoute = DashboardPaceRouteImport.update({
  id: '/pace',
  path: '/pace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHeartRateRoute = DashboardHeartRateRouteImport.update({
  id: '/heart-rate',
  path: '/heart-rate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCadenceRoute = DashboardCadenceRouteImport.update({
  id: '/cadence',
  path: '/cadence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivitiesRoute = DashboardActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthStravaRoute = AuthStravaRouteImport.update({
  id: '/auth/strava',
  path: '/auth/strava',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncStreamRoute = ApiSyncStreamRouteImport.update({
  id: '/api/sync/stream',
  path: '/api/sync/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaWebhookRoute = ApiStravaWebhookRouteImport.update({
  id: '/api/strava/webhook',
  path: '/api/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/strava': typeof AuthStravaRoute
  '/dashboard/activities': typeof DashboardActivitiesRoute
  '/dashboard/cadence': typeof DashboardCadenceRoute
  '/dashboard/heart-rate': typeof DashboardHeartRateRoute
  '/dashboard/pace': typeof DashboardPaceRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/api/sync/stream': typeof ApiSyncStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/strava': typeof AuthStravaRoute
  '/dashboard/activities': typeof DashboardActivitiesRoute
  '/dashboard/cadence': typeof DashboardCadenceRoute
  '/dashboard/heart-rate': typeof DashboardHeartRateRoute
  '/dashboard/pace': typeof DashboardPaceRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/api/sync/stream': typeof ApiSyncStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/strava': typeof AuthStravaRoute
  '/dashboard/activities': typeof DashboardActivitiesRoute
  '/dashboard/cadence': typeof DashboardCadenceRoute
  '/dashboard/heart-rate': typeof DashboardHeartRateRoute
  '/dashboard/pace': typeof DashboardPaceRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/api/sync/stream': typeof ApiSyncStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/auth/strava'
    | '/dashboard/activities'
    | '/dashboard/cadence'
    | '/dashboard/heart-rate'
    | '/dashboard/pace'
    | '/dashboard/records'
    | '/dashboard/'
    | '/api/strava/webhook'
    | '/api/sync/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/callback'
    | '/auth/strava'
    | '/dashboard/activities'
    | '/dashboard/cadence'
    | '/dashboard/heart-rate'
    | '/dashboard/pace'
    | '/dashboard/records'
    | '/dashboard'
    | '/api/strava/webhook'
    | '/api/sync/stream'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/auth/strava'
    | '/dashboard/activities'
    | '/dashboard/cadence'
    | '/dashboard/heart-rate'
    | '/dashboard/pace'
    | '/dashboard/records'
    | '/dashboard/'
    | '/api/strava/webhook'
    | '/api/sync/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStravaRoute: typeof AuthStravaRoute
  ApiStravaWebhookRoute: typeof ApiStravaWebhookRoute
  ApiSyncStreamRoute: typeof ApiSyncStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pace': {
      id: '/dashboard/pace'
      path: '/pace'
      fullPath: '/dashboard/pace'
      preLoaderRoute: typeof DashboardPaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/heart-rate': {
      id: '/dashboard/heart-rate'
      path: '/heart-rate'
      fullPath: '/dashboard/heart-rate'
      preLoaderRoute: typeof DashboardHeartRateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cadence': {
      id: '/dashboard/cadence'
      path: '/cadence'
      fullPath: '/dashboard/cadence'
      preLoaderRoute: typeof DashboardCadenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activities': {
      id: '/dashboard/activities'
      path: '/activities'
      fullPath: '/dashboard/activities'
      preLoaderRoute: typeof DashboardActivitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/strava': {
      id: '/auth/strava'
      path: '/auth/strava'
      fullPath: '/auth/strava'
      preLoaderRoute: typeof AuthStravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/stream': {
      id: '/api/sync/stream'
      path: '/api/sync/stream'
      fullPath: '/api/sync/stream'
      preLoaderRoute: typeof ApiSyncStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/webhook': {
      id: '/api/strava/webhook'
      path: '/api/strava/webhook'
      fullPath: '/api/strava/webhook'
      preLoaderRoute: typeof ApiStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivitiesRoute: typeof DashboardActivitiesRoute
  DashboardCadenceRoute: typeof DashboardCadenceRoute
  DashboardHeartRateRoute: typeof DashboardHeartRateRoute
  DashboardPaceRoute: typeof DashboardPaceRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivitiesRoute: DashboardActivitiesRoute,
  DashboardCadenceRoute: DashboardCadenceRoute,
  DashboardHeartRateRoute: DashboardHeartRateRoute,
  DashboardPaceRoute: DashboardPaceRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStravaRoute: AuthStravaRoute,
  ApiStravaWebhookRoute: ApiStravaWebhookRoute,
  ApiSyncStreamRoute: ApiSyncStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
