/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthStravaRouteImport } from './routes/auth/strava'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiSyncStreamRouteImport } from './routes/api/sync/stream'
import { Route as ApiStravaWebhookRouteImport } from './routes/api/strava/webhook'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStravaRoute = AuthStravaRouteImport.update({
  id: '/auth/strava',
  path: '/auth/strava',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncStreamRoute = ApiSyncStreamRouteImport.update({
  id: '/api/sync/stream',
  path: '/api/sync/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaWebhookRoute = ApiStravaWebhookRouteImport.update({
  id: '/api/strava/webhook',
  path: '/api/strava/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/strava': typeof AuthStravaRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/api/sync/stream': typeof ApiSyncStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/strava': typeof AuthStravaRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/api/sync/stream': typeof ApiSyncStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/strava': typeof AuthStravaRoute
  '/api/strava/webhook': typeof ApiStravaWebhookRoute
  '/api/sync/stream': typeof ApiSyncStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/auth/strava'
    | '/api/strava/webhook'
    | '/api/sync/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/auth/strava'
    | '/api/strava/webhook'
    | '/api/sync/stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/auth/strava'
    | '/api/strava/webhook'
    | '/api/sync/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStravaRoute: typeof AuthStravaRoute
  ApiStravaWebhookRoute: typeof ApiStravaWebhookRoute
  ApiSyncStreamRoute: typeof ApiSyncStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/strava': {
      id: '/auth/strava'
      path: '/auth/strava'
      fullPath: '/auth/strava'
      preLoaderRoute: typeof AuthStravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/stream': {
      id: '/api/sync/stream'
      path: '/api/sync/stream'
      fullPath: '/api/sync/stream'
      preLoaderRoute: typeof ApiSyncStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/webhook': {
      id: '/api/strava/webhook'
      path: '/api/strava/webhook'
      fullPath: '/api/strava/webhook'
      preLoaderRoute: typeof ApiStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStravaRoute: AuthStravaRoute,
  ApiStravaWebhookRoute: ApiStravaWebhookRoute,
  ApiSyncStreamRoute: ApiSyncStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
